name: 'Lashbrookanen '
favicon: null
layout_spectrum: 0.8338026767596602
typography_spectrum: 0.6391888651996851
title: We are attempting to see the world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#383a37'
    - '#aab8c3'
    - '#697575'
    - '#a69b7f'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
